name: Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint
      - run: npx playwright install firefox --with-deps
      - run: npm test
        env:
          VITE_BROWSER_PROVIDER: playwright
